name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Find and Replace
      run: (Get-Content SheetsAPIController.cs) -replace 'asf = "replace_me"', 'asf = "${{ secrets.SHEETS_CREDENTIALS_2 }}"' | Out-File -encoding UTF8 SheetsAPIController.cs
    - name: prit 
      run: type SheetsAPIController.cs
    - name: Publish
      run: dotnet publish -c release -o bin\publish
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'release.zip'
        path: 'bin\publish'
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        files: "release.zip"
